### ISSUE TITLE
Problems with TypeScript 2.1.4

### ISSUE THREAD

**Issue by bhanu7755** [angular/protractor#3834]
Hi,

There is a problem with running e2e test cases after updating typescript to 2.1.4 .  Here is the error i'm getting 

Error: TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'hammerjs'. (2688)
Cannot find type definition file for 'jasmine'. (2688)
Cannot find type definition file for 'node'. (2688)
Cannot find type definition file for 'selenium-webdriver'. (2688)
Cannot find type definition file for 'source-map'. (2688)
Cannot find type definition file for 'uglify-js'. (2688)
Cannot find type definition file for 'webpack'. (2688)
 Cannot find name 'describe'. (2304)
 Cannot find name 'beforeEach'. (2304)
 Cannot find name 'it'. (2304)
 Cannot find name 'expect'. (2304)
 Cannot find name 'it'. (2304)
 Cannot find name 'expect'. (2304)
 Cannot find name 'it'. (2304)
 Cannot find name 'expect'. (2304)

Bug report

- Protractor Version: `4.0.13`
- Angular Version: `2.3.1`
- Browser(s): `Chrome`

**Comment by cnishina** [comment]
Using the [Protractor cookbook typescript example](https://github.com/angular/protractor-cookbook/tree/master/protractor-typescript) as a starting point, I cannot reproduce this:

edited package.json (update to typescript 2.1.4 and the latest version of Protractor):
```
{
  "name": "protractor-typescript",
  "version": "1.0.0",
  "description": "a protractor with typescript example",
  "main": "conf.js",
  "scripts": {
    "pretest": "npm run tsc && webdriver-manager update",
    "test": "npm run test-example && npm run test-example-on-prepare",
    "test-example": "protractor tmp/example/config.js",
    "test-example-on-prepare": "protractor tmp/example-on-prepare/config.js",
    "tsc": "tsc"
  },
  "author": "Craig Nishina <craig.nishina@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "jasmine": "^2.4.1",
    "protractor": "4.0.13",
    "typescript": "^2.1.4"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.31",
    "@types/node": "^6.0.35"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "declaration": false,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "tmp",
    "types": ["jasmine", "node"]
  },
  "exclude": [
    "node_modules"
  ]
}
```

This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
