### ISSUE TITLE
PhantomJS sometimes crashes

### ISSUE THREAD

**Issue by mcalthrop** [angular/protractor#557]
I have been successfully running a fairly comprehensive suite of Protractor e2e tests using Chrome on OSX (Mavericks: 10.9.2).

We have a technical requirement to run these tests headlessly, so I swapped in PhantomJS instead of Chrome, and after 20 seconds (consistently), I get the following error:

```
Runner Process Exited With Error Code: 8
Fatal error: protractor exited with code: 1
```

Now for some more detailed information.

Here is the full error output from the `grunt` task I am running:
```
Running "protractor:phantomjs" (protractor) task
------------------------------------
PID: 9678 (capability: phantomjs #1)
------------------------------------
Starting selenium standalone server...
Selenium standalone server started at http://192.168.1.111:4444/wd/hub
/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1562
throw error;
^
UnknownError: null
at new bot.Error (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
at Object.bot.response.checkResponse (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
at /path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:135:24
at /path/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
at webdriver.promise.ControlFlow.runInNewFrame_ (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1455:20)
at notify (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
at notifyAll (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
at fulfill (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
at /path/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
at webdriver.promise.ControlFlow.runInNewFrame_ (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1455:20)
==== async task ====
    WebDriver.createSession()
at Function.webdriver.WebDriver.acquireSession_ (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:132:49)
at Function.webdriver.WebDriver.createSession (/path/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
at Builder.build (/path/node_modules/protractor/node_modules/selenium-webdriver/builder.js:105:20)
at LocalDriverProvider.getDriver (/path/node_modules/protractor/lib/driverProviders/local.dp.js:128:9)
at /path/node_modules/protractor/lib/runner.js:327:35
at _fulfilled (/path/node_modules/protractor/node_modules/q/q.js:797:54)
at self.promiseDispatch.done (/path/node_modules/protractor/node_modules/q/q.js:826:30)
at Promise.promise.promiseDispatch (/path/node_modules/protractor/node_modules/q/q.js:759:13)
at /path/node_modules/protractor/node_modules/q/q.js:573:44
    [launcher] Runner Process Exited With Error Code: 8
>>
Fatal error: protractor exited with code: 1
```

Package versions:
```
"grunt-protractor-runner": "~0.2.3"
"protractor": "0.19.0"
"selenium-webdriver": "~2.40"
```

Contents of `protractor.conf.js`:
``` javascript
exports.config = {
    seleniumServerJar: '../../node_modules/protractor/selenium/selenium-server-standalone-2.39.0.jar',
    seleniumPort: 4444,
    seleniumArgs: ['-browserTimeout=60'],
    specs: [
        '../e2e/utils.js',
        '../e2e/**/*-suite.js'
    ],
    capabilities: {
        browserName: 'phantomjs',
        'phantomjs.binary.path': './node_modules/karma-phantomjs-launcher/node_modules/phantomjs/bin/phantomjs',
        'phantomjs.cli.args': ['--debug=true', '--webdriver', '--webdriver-logfile=webdriver.log', '--webdriver-loglevel=DEBUG']
    },
    baseUrl: 'http://localhost:9292',
    rootElement: 'body',
    onPrepare: function () {
        require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter('test/results/', true, true));
    },
    framework: 'jasmine',
    jasmineNodeOpts: {
        onComplete: function () {
        },
        isVerbose: true,
        showColors: true,
        includeStackTrace: true,
        defaultTimeoutInterval: 30000
    }
};
```

I have tried installing version `~1.9.7-1` of the `phantomjs` package independently of the one that `protractor` depends upon, and updating the `phantomjs.binary.path` property in `protractor.conf.js`, but I get the same result.

After spending far too long debugging the JS to try to isolate where the error is occurring, I know that it is falling over in `runner.js`.

Specifically in `Runner.prototype.runJasmine_()`, the anonymous function passed to `webdriver.promise.controlFlow().execute()` [here](https://github.com/angular/protractor/blob/master/lib/runner.js#L38-L39) is never executed.

Can anyone help?

Let me know if you need more information.

Matt

**Comment by juliemr** [comment]
Hi folks, I just want to give an update here. Protractor does NOT test against PhantomJS in our CI environment, and while we'll try to address issues and look at pull requests that improve PhantomJS problems, it is not a high issue for the core team to work on personally.

In issue detro/ghostdriver#328 the phantom devs said some of this instability would be addressed with PhantomJS 2.0.

**Comment by natkrish** [comment]
I am getting same error when running my protractor cucumber js framework using phantomjs.  Error while running module script protractorBaseModule_: Error communicating with the remote browser. It may have died. 
Does anyone know whether this issue has been fixed?

**Comment by nextdoor-engineer** [comment]
me too. I'm using nightwatch and running my tests against phantomJs

**Comment by dotjose** [comment]
I have been working on protractor and when I used firefox browser to run my test specs on all my tests have passed. But when I used phantomjs to all my test specs that have been passed on firefox have failed and returns an error code 1. 
Does any one who have faced such an issue and fix it?

**Comment by bentolor** [comment]
I experience _reproducable_ this crash on a CI server **after upgrading from PhantomJS 1.9.18 to 1.9.19.** 

````
build	30-Nov-2015 16:18:20	/data/jira/bamboo-home/xml-data/build-dir/XX-DASH-CLIENTCI/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
build	30-Nov-2015 16:18:20	  var template = new Error(this.message);
build	30-Nov-2015 16:18:20	                 ^
build	30-Nov-2015 16:18:20	UnknownError: Session [8a8ef2a0-9775-11e5-ad8a-89605c3acb91] was terminated due to FORWARDING_TO_NODE_FAILED
build	30-Nov-2015 16:18:20	    at new bot.Error (/data/jira/bamboo-home/xml-data/build-dir/XX-DASH-CLIENTCI/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
build	30-Nov-2015 16:18:20	    at Object.bot.response.checkResponse (/data/jira/bamboo-home/xml-data/build-dir/XX-DASH-CLIENTCI/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
build	30-Nov-2015 16:18:20	    at /data/jira/bamboo-home/xml-data/build-dir/XX-DASH-CLIENTCI/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20
    ...
build	30-Nov-2015 16:18:20	[launcher] Process exited with error code 1
````

Interestingly it does not crash if I execute the very same command in a terminal session on the very same server nor on my own PC. Downgrading did help.

**Comment by artemjackson** [comment]
Same issue on Phantomjs 1.9.19 but it works on 1.9.18

**Comment by jpaulin** [comment]
+1 Good work! 

Had for a small time this showstopper bug too. 

Then karma to: 0.13.19 works for me too. Thank you!

I had a "Missing error handler on `socket`. TypeError: sockets.forEach is not a function" 
while building a project, which had essentially devDependencies as:

"devDependencies": {
    "angular-gettext": "2.1.2",
    "glob": "6.0.1",
    "grunt": "0.4.5",
    "grunt-angular-gettext": "2.1.3",
    "grunt-bower-task": "0.4.0",
    "grunt-cli": "0.1.13",
    "grunt-contrib-clean": "0.7.0",
    "grunt-contrib-concat": "0.5.1",
    "grunt-contrib-copy": "0.8.2",
    "grunt-contrib-jshint": "0.11.3",
    "grunt-contrib-less": "1.1.0",
    "grunt-contrib-requirejs": "0.4.4",
    "grunt-contrib-uglify": "0.11.0",
    "grunt-contrib-watch": "0.6.1",
    "grunt-dependo": "0.1.2",
    "grunt-express": "1.4.1",
    "grunt-istanbul": "0.6.1",
    "grunt-karma": "0.12.1",
    "grunt-karma-sonar": "0.2.17",
    "grunt-newer": "1.1.1",
    "grunt-ngdocs": "0.2.9",
    "grunt-open": "0.2.3",
    "grunt-preprocess": "5.0.1",
    "grunt-protractor-runner": "2.1.0",
    "jasmine-reporters": "2.0.7",
    "jasmine-spec-reporter": "2.4.0",
    "json-proxy": "0.9.1",
    "karma": "0.13.19",
    "karma-chrome-launcher": "0.2.1",
    "karma-coverage": "0.5.3",
    "karma-firefox-launcher": "0.1.7",
    "karma-ie-launcher": "0.2.0",
    "karma-jasmine": "0.3.6",
    "karma-junit-reporter": "0.3.3",
    "karma-phantomjs-launcher": "0.2.1",
    "karma-requirejs": "0.2.2",
    "karma-spec-reporter": "0.0.22",
    "load-grunt-tasks": "3.3.0",
    "npm-check-updates": "2.5.1",
    "phantomjs": "1.9.18",

    "protractor": "2.5.1",

    "protractor-screenshot-reporter": "0.0.5",
    "requirejs": "2.1.22",
    "updatehammer": "0.3.4",
    "webdriver": "0.0.1"
  }

**Comment by cjeffers** [comment]
I don't have the problem with PhantomJS 1.9.18, but when upgrading to 1.9.19 it fails about half the time, after a successful call to `browser.get('/')`, with the following error:
```
Uncaught exception: Error while running module script protractorBaseModule_: Error communicating with the remote browser. It may have died.
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
```

**Comment by cjeffers** [comment]
I was having the same issue with PhantomJS 1.9.x, but it appears* to be fixed by upgrading to the latest version of PhantomJS (2.1.3 currently). If this was the fix, it appears the issue lies with PhantomJS. Further, since it appears to be fixable by upgrading, could this issue potentially be closed? 

*no failures in 10 runs of a suite that failed on ~40% of runs with 1.9.x. If this doesn't seem significant enough to justify the label "fixed", I can do more runs.

**Comment by joaoffalcao** [comment]
As @cjeffers said, after upgrading to PhantomJS 2.1.3, this issue doesn't happened anymore.

**Comment by heroandtn3** [comment]
Yes, this is fixed by upgrade to PhantomJS 2 https://github.com/detro/ghostdriver/issues/328#issuecomment-44309690

**Comment by NickTomlin** [comment]
I'll go ahead and close the loop here because upgrading to PhantomJS 2 resolves this 👏 👏 🎊 🎺

I'd also like to restate what Julie mentioned earlier: 

> Protractor does NOT test against PhantomJS in our CI environment, and while we'll try to address issues and look at pull requests that improve PhantomJS problems, it is not a high issue for the core team to work on personally.

If anyone encounters additional issues with Phantom, please try to raise an issue on the Phantom queue and resolve it there. Thanks, y'all are awesome! 😺
