### ISSUE TITLE
Protractor 7.0 issues

### ISSUE THREAD

**Issue by munna73** [angular/protractor#5452]
I am unable to upload file with protractor version 7. My script fails driver.execute is not a function.

Same ciode works fine on a machine with Protractor 5.4.2, Node Version 8.11.3

node --version

v12.18.2

npm --version

6.14.5

protractor --version

7.0.0

chrome version

Version 83.0.4103.116 (Official Build) (64-bit)

My Upload file code this was working before.

this.uploadfile = function (pathtofile) {

browser.setFileDetector(new remote.FileDetector());

absolutePath = path.resolve(__dirname, pathtofile);

console.log('Absolute File Path : ' + absolutePath);

elem = element(by.xpath("//input[@class='sr-only' and @type='file']"));

elem.sendKeys(absolutePath);

}

Please help.

[16:37:06] W/element - more than one element found for locator By(xpath, //input[@class='sr-only' and @type='file']) - the first result will be used

  Top level suite

    ×  Test

      - Failed: driver.execute is not a function

          at C:\Automation\myuiautomation\node_modules\selenium-webdriver\remote\index.js:605:27

      From: Task: WebElement.sendKeys()

          at WebElement.sendKeys (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2185:43)

          at actionFn (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\built\element.js:89:44)

          at Array.map (<anonymous>)

          at C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\built\element.js:461:65

          at ManagedPromise.invokeCallback_ (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)

          at TaskQueue.execute_ (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)

          at TaskQueue.executeNext_ (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)

          at C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27

          at C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7

          at processTicksAndRejections (internal/process/task_queues.js:97:5)Error

          at ElementArrayFinder.applyAction_ (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)

          at ElementArrayFinder.<computed> [as sendKeys] (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)

          at ElementFinder.<computed> [as sendKeys] (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)

          at utilities.uploadfile (C:\Automation\myuiautomation\src\utils\utilities.js:198:8)

          at ditionPage.uploadTargetListDialog (C:\Automation\myuiautomation\src\pages\dition.js:714:9)

          at CreateOrderPage.uploadList (C:\Automation\myuiautomation\src\pages\CreateOrder.js:708:14)

          at UserContext.<anonymous> (C:\Automation\myuiautomation\src\testspec\Temp.js:83:17)

          at new ManagedPromise (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)

          at ControlFlow.promise (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)

      From: Task: Run it(" Test ") in control flow

          at ControlFlow.emit (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\events.js:62:21)

          at ControlFlow.shutdown_ (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2674:10)

          at C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2599:53

      From asynchronous test:

      Error

          at Object.<anonymous> (C:\Automation\myuiautomation\src\testspec\Temp.js:81:1)

          at Module._compile (internal/modules/cjs/loader.js:1138:30)

          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

          at Module.load (internal/modules/cjs/loader.js:986:32)

          at Function.Module._load (internal/modules/cjs/loader.js:879:14)

          at Module.require (internal/modules/cjs/loader.js:1026:19)

          at require (internal/modules/cjs/helpers.js:72:18)

          at Array.forEach (<anonymous>)

**************************************************

*                    Failures                    *

**************************************************

1)  Test

  - Failed: driver.execute is not a function

**Comment by nitika18** [comment]
Yes, even we are facing the same issue.

**Comment by nitika18** [comment]
This is happening with me with latest selenium webdriver version ^4.0.0-alpha.8

**Comment by apurwar15** [comment]
If I observer closely the mentioned error

"  **- Failed: driver.execute is not a function
 at C:\Automation\myuiautomation\node_modules\selenium-webdriver\remote\index.js:605:27

_From: Task: WebElement.sendKeys()
 at WebElement.sendKeys (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2185:43)**_"

It is using two different path to connect with selenium-webdriver..and  first one is the latest selenium-webdriver (selenium-webdriver@4.0.0-alpha.8)
Failed: driver.execute is not a function
 at C:\Automation\myuiautomation\node_modules\selenium-webdriver\remote\index.js:605:27

and Second one is the old one which Protractor internally uses
t WebElement.sendKeys (C:\Users\abcdmyid\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2185:43

 If I remove the latest selenium-webdriver from node-modules and then use protractor latest version... I am not getting this error.

**Comment by mrkjdy** [comment]
I tried using the remote in protractors node_modules, but I get a File not found error:
```
- Failed: invalid argument: File not found : /tmp/session614065523581573828156746de5505c305830094cb3b1691ec4/upload8301810421599486060file/.DS_Store
    (Session info: headless chrome=88.0.4324.150)
    (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Linux 4.19.121-linuxkit x86_64)
```
